### ISSUE TITLE
how to contact?

### ISSUE THREAD

**Issue by nikuscs** [Suraxius/darkmatterbot#17]
Looking to help or maintain the project , how to get in contact with you?

**Comment by Suraxius** [comment]
Hey mate, sorry for the  delay. Id appreciate any help you can give.
Feel free to contact me by email. when you clone with git you can see my email as part of my commits (I dont want email address crawlers to pick it up by posting it here).
I am currently working on the libOgame part of the project. There is an issue with the HTTPSClient class which prevents successful login handling. I am experimenting with both the apache httpclient and  HttpsURLConnection approaches. I could give you write access to the repo if you like to contribute. There are many aspects of the project which are fairly simple to implement but for which i did not have time to work on yet (specifically UI elements of the Android and JavaFX interfaces).
